Updated tools from scripts directory.

diff --git a/git-branch-delete b/git-branch-delete
--- a/git-branch-delete
+++ b/git-branch-delete
@@ -3,7 +3,27 @@ set -euo pipefail
 
 # E.B.Smith, June 2017  -  Delete a git branch locally and upstream.
 
-branch_name="$1"
+if (( $# == 0 ))
+then
+    printf "Usage: git-branch-delete <branch-name> ...\n" 1>&2
+    exit 0
+fi
+
 git checkout master
-(git push origin --delete "$branch_name" || true)
-git branch -D "$branch_name"
+while (( $# > 0 ))
+do
+    branch_name="$1"
+    if [[ "$branch_name" == remotes/origin/* ]]
+    then
+        branch_name="${branch_name#remotes/origin/}"
+    fi
+    printf "Branch: %s\n" "$branch_name"
+    if [[ "$branch_name" == "master" ]]
+    then
+        printf "Can't delete the master branch." 1>&2
+        exit 1
+    fi
+    (git push origin --delete "$branch_name" || true)
+    (git branch -D "$branch_name" || true)
+    shift
+done
diff --git a/git-branch-make b/git-branch-make
--- a/git-branch-make
+++ b/git-branch-make
@@ -3,6 +3,12 @@ set -euo pipefail
 
 # E.B.Smith, June 2017  -  Create a new git branch from the current branch and push it upstream.
 
+if (( $# != 1 ))
+then
+    echo ">>> Error: One argument is expected, the name of the new branch." 1>&2
+    exit 1
+fi
+
 branch_name="$1"
 git checkout -b "$branch_name"
 git push -u origin "$branch_name"
